### ISSUE TITLE
About image editing in rUGP (Schwarzesmarken)

### ISSUE THREAD

**Issue by MishaIac** [crskycode/GalgameCoding#1]
Hello @crskycode.
Thanks for the article about parsing rugp (though I don't know Chinese, I had to read it using a google translator)
I have one question. Is there any way to edit the graphics in rUGP? I just need this for the Schwarzesmarken. I was prompted to use hooks, but through them I managed to edit only the text, but the images does not work.
Is it possible to write a program that is capable of editing images in .rio files? All the text has long been translated, but since there is a lot of text in the form of graphics in the game, there is no point in releasing a translation without translating the graphics.
As far as I know, almost all games from age, rio archives have the same encryption. And I also know that there can be problems with importing an image into rio that weighs more than the original image, but if you edit the image so that it weighs the same as the original, then it shouldn't be a problem, shouldn't it?
In any case, I need help, because since 2017, translation of the text is finished, but is still hanging in the frozen status.

**Comment by crskycode** [comment]
About the graphics, hook texture uncompress function to extract original image, do the replaces. so reverse the engine to find the function, and hook it. You will need to find a reverse engineer to write the hook.

**Comment by MishaIac** [comment]
But where to find the reverse engineer...
Personally, I'm not a programmer. In fact, there is an open source hook project for rugp, but it does not support rugp 6.2, although the code mentions this version. Maybe it will be easier to rewrite this hook project under rugp 6.2 than to create it from scratch?

By the way, this hook works perfectly on rugp 5.8.

**Comment by crskycode** [comment]
Maybe I can take a look at this open source project. Can you give me a link?

**Comment by MishaIac** [comment]
> Maybe I can take a look at the open source project. Can you give me a link?

https://github.com/eplightning/afhook

**Comment by crskycode** [comment]
Awesome, this project may work with this game, just need to make some modifications.

**Comment by MishaIac** [comment]
> Awesome, this project may work with this game, just need to make some modifications.

Really? Its very good!
Will you modify this project?

**Comment by crskycode** [comment]
> > Awesome, this project may work with this game, just need to make some modifications.
> 
> Really? Its very good!
> Will you modify this project?

My friend @AyamiKaze will try to do it.

**Comment by MishaIac** [comment]
@crskycode @AyamiKaze thanks you very much!

**Comment by MishaIac** [comment]
Hello again. In short, 
I've been trying to get afhook to work with Schwarzesmarken for two weeks now, but alas, nothing works.
If I just take afhook from github unchanged, it only finds DecodeR6TiOpaque1 function judging by the logs, but after the main menu appears, the game immediately crashes. By changing the pattern search for the HandleText function a bit, and removing the search for the DecodeR6TiOpaque1 function, afhook finds HandleText. But, as soon as I start the game and the first line appears, the game crashes.
What am I doing wrong? What is the problem?

And as I understand it, AyamiKaze can't help with this, right?

**Comment by MishaIac** [comment]
Solved.

**Comment by tritiumjngn** [comment]
Hello. If it is ok with you can you tell how you made afhook work on ages 7.0? Thank you.
