### ISSUE TITLE
[Request] Extracting, Editing, and then Repacking "GRD" Files

### ISSUE THREAD

**Issue by VenomMaximus** [crskycode/GalgameCoding#10]
Hello @crskycode 
I would like to be able to properly extract a certain type of image file in the "GRD" format from a visual novel (this one https://vndb.org/v26531), translate it, and then put it back into the game. While trying to extract the GRD files myself, I have discovered a few things.

It's a file type I have never seen before, yet all the games by this company (Lune) seem to use it for their images. My computer recognizes them as "Photoshop Gradient" files, but that's not what they are. GARbro is able to properly view the images and display them, and even extract them from the "pac" files they are located within either "as is" or as PNG or BMP, but GARbro has no method for putting any modified files back in to the pac files. The GRD files also cannot be opened by any program I have even after being extracted from GARbro.
While using another method to try and extract the files (tmr.py found here https://mega.nz/file/qj5zGSpD#XqWXPVgb6IT1Ry60LbjfCLJaJaH7nZ_kPUiFHpmpN7w, I apologize as I do not have any GitHub link for it), I have found that when extracted using tmr.py the grd files extract without any file extension whatsoever, and will be displayed like this.
![fileviewer](https://user-images.githubusercontent.com/57280696/144896184-3b6ef111-436f-4e1d-8dfa-2624342169dd.PNG)

Trying to simply add a "PNG" or "BMP" extension to any of these files does not work, as I would assume. When these files are then repacked into a .pac file using tmr.py, then at first they will look like this inside the newly created pac file.
![prerename](https://user-images.githubusercontent.com/57280696/144896701-1839607d-7b1d-4879-a923-5861eca8484d.PNG)

They are not recognized whatsoever and can't be viewed in GARbro. However, when the .pac file that was just created is then renamed into something like "Agrd" rather than "_new", then suddenly, all the files have the GRD extension placed on them and can be viewed normally.
![postrename](https://user-images.githubusercontent.com/57280696/144896730-2044e5e9-ab5e-4180-99d9-58138f19bae4.PNG)

This is very strange to me, as I have never seen files work like this before. Regardless, what I would like is the ability to extract these GRD files, be able to edit them within a photo editor so that UI elements can be translated, and then repack them so that they can used within the game. 
I would greatly appreciate it if you could figure out a method for this to be possible, thank you. If you require any further information, then I'd be happy to elaborate on any specific points.

**Comment by Cosetto** [comment]
So any news on .grd format?

**Comment by crskycode** [comment]
https://github.com/crskycode/TmrHiro_Tool

**Comment by VenomMaximus** [comment]
> https://github.com/crskycode/TmrHiro_Tool

Thank you!
