### ISSUE TITLE
[Request] Ninki Seiyuu: How to make a pop voice actress [EN] Support

### ISSUE THREAD

**Issue by Veshurik** [crskycode/GalgameCoding#11]
Hello!
Would be nice if you can add support for Ninki Seiyuu EN version of the game, because it has protection, and .exe files seems to be encrypted, so I can't extract English assets. 

Also, if I try to paste KrkrExtract, game doesn't want to run at all (some protection again)?

It's from Steam version with adult patch, except "crack.exe" and KrKrexract files.

![image](https://user-images.githubusercontent.com/26744056/151788492-fb8bb6c2-7018-4b90-8828-6b5b3ca1747f.png)

**Comment by crskycode** [comment]
This game uses a complex encryption algorithm.

**Comment by Cosetto** [comment]
> Hello! Would be nice if you can add support for Ninki Seiyuu EN version of the game, because it has protection, and .exe files seems to be encrypted, so I can't extract English assets.
> 
> Also, if I try to paste KrkrExtract, game doesn't want to run at all (some protection again)?
> 
> Here is the [game](https://drive.google.com/file/d/1orALswWlF11xWhS0AtpBSxLuOYo1BzHR/view), thanks. It's from Steam version with adult patch, except "crack.exe" and KrKrexract files.
> 
> ![image](https://user-images.githubusercontent.com/26744056/151788492-fb8bb6c2-7018-4b90-8828-6b5b3ca1747f.png)

you shouldn't post pirate link here

**Comment by Cosetto** [comment]
> Hello! Would be nice if you can add support for Ninki Seiyuu EN version of the game, because it has protection, and .exe files seems to be encrypted, so I can't extract English assets.
> 
> Also, if I try to paste KrkrExtract, game doesn't want to run at all (some protection again)?
> 
> Here is the [game](https://drive.google.com/file/d/1orALswWlF11xWhS0AtpBSxLuOYo1BzHR/view), thanks. It's from Steam version with adult patch, except "crack.exe" and KrKrexract files.
> 
> ![image](https://user-images.githubusercontent.com/26744056/151788492-fb8bb6c2-7018-4b90-8828-6b5b3ca1747f.png)

There's another method to make the game read patch.xp3 without encryption. https://github.com/arcusmaximus/KirikiriTools/releases Use xp3pack to pack, after that copy patch.xp3 and version.dll to the game folder

**Comment by Veshurik** [comment]
Sorry, I don't need pack files, I only need to extract files and decrypt them.

**Comment by Cosetto** [comment]
> Sorry, I don't need pack files, I only need to extract files and decrypt them.

Krkrextract doesn't work?

**Comment by Veshurik** [comment]
> > Sorry, I don't need pack files, I only need to extract files and decrypt them.
> 
> Krkrextract doesn't work?

Nope. Even if somehow I can let it run, extracted files still encrypted

**Comment by crskycode** [comment]
I found the anti-debugger code in `seiyuu.tpm`. If this plugin finds the debugger, it will change the key used to decrypt the file, so you will get the incorrect file. However, you can try injecting `KrkrExtract` into the game using `x64dbg` and the `ScyllaHide` plugin, which should hide the debugger.

**Comment by Veshurik** [comment]
> 
Oof, we tried, it doesn't help :(

**Comment by crskycode** [comment]
This game from your link doesn't work on my PC, so I can't analyze it further.

**Comment by Veshurik** [comment]
> This game from your link doesn't work on my PC, so I can't analyze it further.

That's sad, but anyway, thanks for the help!

**Comment by MishaIac** [comment]
> I found the anti-debugger code in seiyuu.tpm. If this plugin finds the debugger, it will change the key used to decrypt the file, so you will get the incorrect file.

You mean this?
![image](https://user-images.githubusercontent.com/47920105/151971737-1f595d04-953b-4fda-bfce-58cac91f3183.png)

**Comment by Cosetto** [comment]
> This game from your link doesn't work on my PC, so I can't analyze it further.

Can you also add support for hello lady(Steam) version? https://vndb.org/v13631

**Comment by crskycode** [comment]
> > This game from your link doesn't work on my PC, so I can't analyze it further.
> 
> Can you also add support for hello lady(Steam) version? https://vndb.org/v13631

No, i don't have this game.

**Comment by Cosetto** [comment]
> > > This game from your link doesn't work on my PC, so I can't analyze it further.
> > 
> > 
> > Can you also add support for hello lady(Steam) version? https://vndb.org/v13631
> 
> No, i don't have this game.

I've emailed you the game

**Comment by Veshurik** [comment]
> > I found the anti-debugger code in seiyuu.tpm. If this plugin finds the debugger, it will change the key used to decrypt the file, so you will get the incorrect file.
> 
> You mean this? ![image](https://user-images.githubusercontent.com/47920105/151971737-1f595d04-953b-4fda-bfce-58cac91f3183.png)

So it means you can just delete these lines, and send updated .tpm? To extract game then

**Comment by crskycode** [comment]
> > > I found the anti-debugger code in seiyuu.tpm. If this plugin finds the debugger, it will change the key used to decrypt the file, so you will get the incorrect file.
> > 
> > 
> > You mean this? ![image](https://user-images.githubusercontent.com/47920105/151971737-1f595d04-953b-4fda-bfce-58cac91f3183.png)
> 
> So it means you can just delete these lines, and send updated .tpm? To extract game then

I know how to bypass the debugger checks. But the game you uploaded doesn't work on my PC, even without using any debugger.

**Comment by crskycode** [comment]
Solved. See https://github.com/crskycode/GARbro/releases/tag/GARbro-Mod-1.0.0.4

**Comment by crskycode** [comment]
I rewrite the tpm, all anti-debugger code removed, and game.exe also unpacked.
[Ninki Seiyuu Unpack.zip](https://github.com/crskycode/GalgameCoding/files/8061763/Ninki.Seiyuu.Unpack.zip)

**Comment by Veshurik** [comment]
Thank you veru much!
