### ISSUE TITLE
KaGuYa

### ISSUE THREAD

**Issue by suguhara** [crskycode/GalgameCoding#2]
Your tools are great man, keep it up. But I just want to ask is there any tool for Atelier Kaguya? If don't you can close this =((

**Comment by crskycode** [comment]
I don’t have this company’s games. Maybe in the future. Can you give me a vndb link?

**Comment by suguhara** [comment]
> I don’t have this company’s games. Maybe in the future. Can you give me a vndb link?

https://vndb.org/p171 they have a famous game called mama x holic and also some of their vns have chinese patch like: https://vndb.org/v26530

**Comment by suguhara** [comment]
Also your friend Ayamikaze has a code of KaGuYa engine https://github.com/AyamiKaze/Galgame_Project/blob/master/KAGUYA/extKAGUYA_SCR.cpp. Here some screenshot about their engine 
![image](https://user-images.githubusercontent.com/81801486/134442735-68a444ce-a86a-48c3-9278-c44085662b04.png)
![image](https://user-images.githubusercontent.com/81801486/134442762-99f0d787-e6f8-42ab-a942-17ea56f59947.png)

**Comment by suguhara** [comment]
Sorry for bothering you again but do you know this tool, it seems can extract bsxx.dat from https://vndb.org/p215. I'm wondering if it can do the same with KaGuYa but the problem is I can't find it anywhere.
![image](https://user-images.githubusercontent.com/81801486/134606398-0b58d68d-4011-4913-8b63-1f614a741f01.png)

**Comment by suguhara** [comment]
[2012_v3.4.zip](https://github.com/crskycode/GalgameCoding/files/7226727/2012_v3.4.zip)
Found it but it is written in chinese and the only thing I know is exporting txt

**Comment by crskycode** [comment]
I created a new tool for Kaguya's game.
But currently it only supports newer file versions.
Before using this tool, you should first use any HexEditor to check the `message.dat` file header, like this.
![20210928214421](https://user-images.githubusercontent.com/21205962/135099053-bab7cdeb-c9d9-4fc0-bd0d-af21dbeaf224.png)
This tool only supports `message.dat` with version 4.0.

**Comment by suguhara** [comment]
> I created a new [tool](https://github.com/crskycode/Kaguya_Tool) for Kaguya's game. But currently it only supports newer file versions. Before using this tool, you should first use any HexEditor to check the `message.dat` file header, like this. ![20210928214421](https://user-images
[srp.zip](https://github.com/crskycode/GalgameCoding/files/7244777/srp.zip)
.githubusercontent.com/21205962/135099053-bab7cdeb-c9d9-4fc0-bd0d-af21dbeaf224.png) This tool only supports `message.dat` with version `4.0`.

omg thanks you so much, you're the best. Can you add repack option for this https://github.com/crskycode/GARbro/tree/master/ArcFormats/Tmr-Hiro. This engine is used by https://vndb.org/p490 and https://vndb.org/p258. Here a sample, it's from this https://vndb.org/v19620. I'll close this issue

**Comment by Cosetto** [comment]
Can you also make tool for .alp? Seems like some buttons can't read bmp neither png, GARbro converts .alp into .png with right scale but .bmp isn't right
![image](https://user-images.githubusercontent.com/81801486/140850797-27d56a83-e457-4c57-89de-86b6d0b92503.png)

**Comment by crskycode** [comment]
Added Kaguya ALG tool.
