### ISSUE TITLE
BISHOP BSXScript support

### ISSUE THREAD

**Issue by xenei** [crskycode/GalgameCoding#3]
Hello CrSkyCode,
I've been recently trying to translate and hack into BISHOP titles.. but I wasn't able to at first because of no tools available... But One of my CN friend gave me this tool called "Siniciaztion Toolbox 2012" by 天诛熊, I've trying to use but unfortunately I believe it wasn't made for english text modification because no matter how ever I use it I can't inject more than 4 words or some particular number of characters... and I absolutely can't figure out why... and I believe there's no other tools avail for these BISHOP titles.
I was hoping if you could figure out why isn't it working or if I am doing anything wrong ― I was trying the tool on this VN- https://vndb.org/v11916 , 
Here's the "Siniciaztion Toolbox 2012" by 天诛熊 tool both Original and a half attempt at trying to TL into english one ― 
 Original - [2012_v3.4.zip](https://github.com/crskycode/GalgameCoding/files/7474704/2012_v3.4.zip)
English - [Textmogrifier v0.3.zip](https://github.com/crskycode/GalgameCoding/files/7474698/Textmogrifier.v0.3.zip)

I would be very grateful to you if you can hack into BISHOP titles... because the Community greatly demands it and the last translator who ever TL'ed it can't share his tool due to because the original hacker asked him not to....

**Comment by crskycode** [comment]
I created a new [tool](https://github.com/crskycode/BSXScript_Tool
) for this game. Hope it helps you.

About the window title, it hard code in `startup.exe`, this program will write the title string to a binary file.

```
C:\Users\xxxx\AppData\Local\BISHOP\MK3\bsxx.ini
```

You can use a HexEditor to modify it.

#### Before

![image](https://user-images.githubusercontent.com/21205962/140600330-d0046f91-9fc8-4e36-b175-ebc1a3289753.png)

#### After

![image](https://user-images.githubusercontent.com/21205962/140600379-c752f85a-f98c-4fb3-98dd-ed6f54e0d15c.png)

#### Preview

![image](https://user-images.githubusercontent.com/21205962/140600403-8bb292d8-46f5-4326-bb9e-f8a58eaca5e0.png)

**Comment by xenei** [comment]
Wow... your tool is working flawlessly, I'm so happy that I can't even express it in words anymore... Thank you so much!
![happy](https://user-images.githubusercontent.com/91423244/140605100-bf3d10af-9d19-48df-a864-b662f277b262.PNG)
