### ISSUE TITLE
Tactic Engine

### ISSUE THREAD

**Issue by DesonimerZ** [crskycode/GalgameCoding#4]
Hello, so i was trying to unpack file from "Innocent bullet the false world", and the engine name in garbro when i open it is named "Tactics" .... 
When i open the arc file with garbro it works fine, but the file for translate text is .bin and i don't know how to unpack or open with.
![image](https://user-images.githubusercontent.com/70036747/140612100-1507c1d9-cb41-40c8-89f5-2f882b737609.png)

Can you help me unpack the script of this engine?

**Comment by crskycode** [comment]
This game protected with Settec AlphaROM, so i can't analyze it.

**Comment by crskycode** [comment]
I created a new tool for the script of this engine. Limited by the format of the script, I cannot guarantee the versatility of this tool, and errors may occur at any time.

Tool https://github.com/crskycode/Tactics_Script_Tool

**Comment by DesonimerZ** [comment]
hello when i running the tools, there was error not found for "gbk"
![image](https://user-images.githubusercontent.com/70036747/140678327-7bcb7f07-e3ef-447a-9211-1828aa705a4b.png)

**Comment by crskycode** [comment]
PLEASE SEE [README](https://github.com/crskycode/Tactics_Script_Tool#usage)

To export text, run tool with three parameters
```
Tactics_Script_Tool -e "shift_jis" "c:\game\bin\00_common_01_01.bin"
```

**Comment by DesonimerZ** [comment]
the export is work well, but whenever i input this line to import, there an error for "gbk"

Here's what i input for import Tactics_Script_Tool -e "shift_jis" "gbk" "C:\Users\gilan\Desktop\v1.0\00_common_01_01.bin"

**Comment by crskycode** [comment]
To import text, use `-b` mode.

**Comment by DesonimerZ** [comment]
nice it works well, but now i need to repack it to arc file, do you know how?

**Comment by crskycode** [comment]
Each game uses a different key to encrypt the archive file, and the format is also different. I don't have a good idea to write a universal repacker.

**Comment by DesonimerZ** [comment]
Ah i see, garbro have the encrypt key for unpacking the arc file, but there is not option to pack the file to arc tactic file ....
