### ISSUE TITLE
.Bsg image support/or converter from png2bsg

### ISSUE THREAD

**Issue by xenei** [crskycode/GalgameCoding#5]
Hello, It's me again. First of all I'm am very thankful that we can translate text easily but...
While we were doing our work, I thought to check the image format a bit and found out they're in .bsg format... which ofcourse can be converted to .png using garbro however the game doesn't read .png file but It can read if it is in .bmp. And since .Bmp images can't have transparency they come and look out like this -
![blank](https://user-images.githubusercontent.com/91423244/140640834-10ee62ed-a80a-4c86-895e-11dd923bb7c9.PNG)

![blanlk2](https://user-images.githubusercontent.com/91423244/140640837-656a6ce9-7470-4ed7-85fc-4010ee273549.PNG)

Which is very unfortunate and doesn't look very appealing to eye... I was wondering If you can add for .bsg format support like converting from .png2.bsg. But at the end of the end I think it is okay if it is not possible we can always have them translated as an extra part of our translation. Again, Thank you for this great tool.

**Comment by crskycode** [comment]
I created a new [tool](https://github.com/crskycode/Bishop_BSG_Tool) to convert PNG to BSG, and it currently only works with UI image files.

**Comment by xenei** [comment]
Wow, It's working flawlessly; honest thanks for this and thank you  -
![wow](https://user-images.githubusercontent.com/91423244/140851590-7ce34ffc-d359-465b-894b-c44555b6e621.PNG)
