### ISSUE TITLE
About .ybn files

### ISSUE THREAD

**Issue by Cosetto** [crskycode/GalgameCoding#6]
Can you make a new script tool from this?
[ybntool.zip](https://github.com/crskycode/YPF_Tool/files/7490719/ybntool.zip)
 It was made by tlwiki in C# in 2013 and specially it can auto guess the key of ybn files( after extract .ypf with GARbro auto guess). I'm surprising that it works with yuris v500 scripts (https://vndb.org/v20416). But it's not stable, sometimes when wrong. The source code is in the zip. Also it would be nice if you can make it dump not only japanese scripts, but also english script too. Here an example
[yst00152.zip](https://github.com/crskycode/YPF_Tool/files/7490752/yst00152.zip)

**Comment by AyamiKaze** [comment]
> > Try this tool https://github.com/regomne/chinesize/tree/master/yuris/extYbn
> 
> I tried but I met memory error cause regomne said it needs key when debug the exe. But I don't know how to do that

Just find the place where decrypt ybn. Key's len is 4.
Other way, if you wanna translate this game. you can connect with me. I'm programmer of Chinese translate project.

**Comment by Cosetto** [comment]
> > > Try this tool https://github.com/regomne/chinesize/tree/master/yuris/extYbn
> > 
> > 
> > I tried but I met memory error cause regomne said it needs key when debug the exe. But I don't know how to do that
> 
> Just find the place where decrypt ybn. Key's len is 4. Other way, if you wanna translate this game. you can connect with me. I'm programmer of Chinese translate project.

Thanks, for now I can get the text, but I have an issue with word wrapping, I have to space for wrapping. Is there anyway to auto wrap it or line break cause \n doesn't work. 
![image](https://user-images.githubusercontent.com/81801486/140843109-eb24524b-095f-4fc3-8cca-51c54231dca8.png)
